version: '3.3'
services:
  db:
    network_mode: host
    image: "mongo:4.0.9"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/usr/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=blackruby
  chat:
    network_mode: host
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:3000"
    env_file:
      - .env